name: Ruby CI

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        #  pick up specific Ruby version from .ruby_version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: rake test && bundle exec rspec spec && rake standard
