
name: Daily Update

on:
  schedule:
    - cron:  '5 10 * * *'

jobs:
  daily:
    name: Daily Updates
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          curl -H 'Authorization: Bearer ${{ secrets.TASKS_TOKEN }}' 'https://booze-hound.fly.dev/tasks/daily'
