
name: Deploy Fly

on:
  workflow_run:
    workflows: [Ruby CI]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: echo 'The Ruby CI workflow passed - ready to deploy'
      - run: echo ${{ github.ref }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  on-ci-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Ruby CI failed - no deploy for you!'
      - run: echo "### NOT deployed :no_entry_sign:" >> $GITHUB_STEP_SUMMARY ; exit 1


